### ISSUE TITLE
should download appropriate .exe for platform

### ISSUE THREAD

**Issue by fschwiet** [SeriousM/WebDriver.ChromeDriver.win32-nuget#8]
It would be great if it used the appropriate .exe per platform.  It may need to add execution permissions (chmod +x) the .exe on mac/linux.

**Comment by SeriousM** [comment]
well, I was never faced the situation before that an other platform than windows was able to use nuget/.net.
Currently there is no way to target linux/mac/win separately (http://docs.nuget.org/create/nuspec-reference).
I guess you need to reference it yourself for the moment, sorry.
