### ISSUE TITLE
A github repository with exe files?

### ISSUE THREAD

**Issue by AndersBillLinden** [SeriousM/WebDriver.ChromeDriver.win32-nuget#9]
Hello!

Sorry if I am asking a stupid question but why do you have a github repository with exe files?

**Comment by AndersBillLinden** [comment]
How do those exe files relate to https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver ?

**Comment by SeriousM** [comment]
Hi, sorry for the delay.

Well, it's easier for everyone to contribute and easier for me to just deploy the current version.
Sure, I could write a program that pulls the latest version from the google chrome page and publish it in one go, but I didn't had time for that icing :)

Do you want to contribute that solution?

**Comment by SeriousM** [comment]
@AndersBillLinden didn't responded with a solution to "the problem", so I'll close this now.
